version: '3'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:3001
      - VITE_ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL}
      - VITE_BSC_RPC_URL=${BSC_RPC_URL}
      - VITE_POLYGON_RPC_URL=${POLYGON_RPC_URL}
      - VITE_ESR_TOKEN_ADDRESS=${ESR_TOKEN_ADDRESS}
      - VITE_PROXY_API_TARGET=http://backend:3001
    restart: always

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    environment:
      - PORT=3001
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@mysql:3306/tokenforge
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - FRONTEND_URL=http://localhost
      - ETHEREUM_RPC_URL=${ETHEREUM_RPC_URL}
      - BSC_RPC_URL=${BSC_RPC_URL}
      - POLYGON_RPC_URL=${POLYGON_RPC_URL}
      - ARBITRUM_RPC_URL=${ARBITRUM_RPC_URL}
      - FANTOM_RPC_URL=${FANTOM_RPC_URL}
      - AVALANCHE_RPC_URL=${AVALANCHE_RPC_URL}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - BSCSCAN_API_KEY=${BSCSCAN_API_KEY}
      - POLYGONSCAN_API_KEY=${POLYGONSCAN_API_KEY}
      - ESR_TOKEN_ADDRESS=${ESR_TOKEN_ADDRESS}
      - PLATFORM_WALLET=${PLATFORM_WALLET}
      - NODE_ENV=production
    restart: always
    volumes:
      - ./deployments:/app/deployments

  # MySQL for persistent storage
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=tokenforge
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: